DayOne/booksStore/book/urls.py
from django.urls import path
from .views import index, show, create ,edit, delete

urlpatterns = [
    path( '' , index , name='index' ),
    path( '<int:bid>/' , show , name='show' ),
    path( 'create/' , create , name='create' ),
    path( '<int:bid>/edit' , edit , name='update' ),
    path( '<int:bid>/destroy' , delete , name='destroy')
]

DayOne/booksStore/booksStore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path( 'books/' , include(('book.urls' , 'book') , namespace='book') )
]

DayOne/booksStore/book/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

books = [
    {'id': 1, 'title': 'Book 1', 'description': 'Description 1'},
    {'id': 2, 'title': 'Book 2', 'description': 'Description 2'},
    {'id': 3, 'title': 'Book 3', 'description': 'Description 3'},
    {'id': 4, 'title': 'Book 4', 'description': 'Description 4'},
    {'id': 5, 'title': 'Book 5', 'description': 'Description 5'},
    {'id': 6, 'title': 'Book 6', 'description': 'Description 6'},
    {'id': 7, 'title': 'Book 7', 'description': 'Description 7'},
    {'id': 8, 'title': 'Book 8', 'description': 'Description 8'},
    {'id': 9, 'title': 'Book 9', 'description': 'Description 9'},
    {'id': 10, 'title': 'Book 10', 'description': 'Description 10'}
]

def index (request) :
    return render (request , 'book/index.html' , context={'books' : books })


def show (request , bid) :
    my_book = find_book(bid)
    return render (request , 'book/show.html' , context={'book' : my_book })



def create (request):
    return HttpResponse('Hello create')

def edit (request , bid) :

    return render (request , 'book/index.html' , context={'books' : books })



def delete (request , bid) :
    delete_book = find_book(bid)
    del books[delete_book["id"] - 1]
    return render (request , 'book/index.html' , context={'books' : books })


def find_book (bid): 
    for book in books:
        if book["id"] == int(bid):
            return book

DayOne/booksStore/templates/book/index.html
{% extends 'layout/app.html' %}
    

{% block title %}
    Books 
{% endblock %}


{% block main-content %}
    <div class="container">
        <div class="row">
            <div class="col-12 ">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Title</th>
                            <th scope="col">Description</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for book in books %}
                            <tr>
                                <td>{{ book.id }}</td>
                                <td>{{ book.title }}</td>
                                <td>{{ book.description }}</td>
                                <td>
                                    <a class="btn btn-info" href="{% url 'book:show' book.id %}">View</a>
                                    <a class="btn btn-success" href="{% url 'book:update' book.id %}">Edit</a>
                                    <a class="btn btn-danger" href="{% url 'book:destroy' book.id %}">Delete</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

DayOne/booksStore/templates/book/show.html
{% extends 'layout/app.html' %}
    

{% block title %}
    Book {{book.id}}
{% endblock %}


{% block main-content %}
    <div class="container">
        <div class="row">
            <div class="col-12 ">
                <li>{{book.id}}</li>
                <li>{{ book.title }}</li>
                <li>{{ book.description }}</li>
            </div>
        </div>
    </div>
{% endblock %}

DayOne/booksStore/templates/layout/app.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Override
        {% endblock %}
    </title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    {% include 'layout/navbar.html' %}

    {%  block main-content  %} 
    
    {% endblock %}

    {% include 'layout/footer.html' %}
</body>
</html>

DayOne/booksStore/templates/layout/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid" style="height: 10vh; background-color: #27374D;">
            
    </div>
</nav>